version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: CRUD app
          command: yarn start
      - run:
          name: Print the Current Time
          command: date
